### ISSUE TITLE
Using the plugin w/ Vagrant

### ISSUE THREAD

**Issue by thijsw** [SiebelsTim/hack-sublime#9]
I was wondering if this plug-in also works if Hack is running in a Vagrant-built VM while the host is OS X (instead of Windows, as stated in the README). I tried myself, but to no avail. Unfortunately, Console does not give any hints at to what might go wrong.

Any suggestions how to get it running using this setup?

**Comment by davidcollingwood** [comment]
Hey, have you had any luck with this since you created this issue? I've just made a couple of updates for this kind of setup recently, except there is one problem I can't resolve. If you are running `hh_client` from your vagrant box, and editing the files locally on OSX, saving the file does not trigger `hh_client` to update. The only way around this problem that I'm aware of, is to install hhvm on your local machine and run `hh_client` locally.

**Comment by SiebelsTim** [comment]
Looks like this is stalled.
